-- MySQL Script generated by MySQL Workbench
-- Tue Dec 13 21:58:02 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema secure-attached-db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema secure-attached-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `secure-attached-db` ;
USE `secure-attached-db` ;

-- -----------------------------------------------------
-- Table `secure-attached-db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `secure-attached-db`.`user` ;

CREATE TABLE IF NOT EXISTS `secure-attached-db`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_email` VARCHAR(45) NULL,
  `user_password` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_email_UNIQUE` (`user_email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `secure-attached-db`.`keys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `secure-attached-db`.`keys` ;

CREATE TABLE IF NOT EXISTS `secure-attached-db`.`keys` (
  `keys_id` INT NOT NULL,
  `keys_content` MEDIUMBLOB NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`keys_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `secure-attached-db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `secure-attached-db`.`history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `secure-attached-db`.`history` ;

CREATE TABLE IF NOT EXISTS `secure-attached-db`.`history` (
  `history_id` INT NOT NULL,
  `history_link` VARCHAR(45) NULL,
  `history_sender` INT NULL,
  `history_receiver` INT NULL,
  PRIMARY KEY (`history_id`),
  UNIQUE INDEX `history_link_UNIQUE` (`history_link` ASC) VISIBLE,
  INDEX `sender_id_idx` (`history_sender` ASC) VISIBLE,
  INDEX `receiver_id_idx` (`history_receiver` ASC) VISIBLE,
  CONSTRAINT `sender_id`
    FOREIGN KEY (`history_sender`)
    REFERENCES `secure-attached-db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `receiver_id`
    FOREIGN KEY (`history_receiver`)
    REFERENCES `secure-attached-db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
